[package]
name = "wlb"
version = "0.1.0"
authors = ["ereichert"]

[dependencies]
iron = "0.4.0"
handlebars-iron = "0.18.0"
env_logger = "0.3.4"
staticfile = "0.3.0"
router = "0.4.0"

[features]
watch = ["handlebars-iron/watch"]